### PR TITLE
Make package available for .net 6 LTS

### PR DESCRIPTION
**Pull request by dannyvolders**
Make package available for .net 6 LTS

### CODE REVIEW

**Comment by ChristianSauer** [comment]
Hi @dannyvolders that looks good.
Can you bump the version tag to 0.6.0 and we will give it a try?
Sorry for the late response, I was on easter vacation

**Comment by ChristianSauer** [comment]
And whats the purpose of Polysharp here?

**Comment by dannyvolders** [comment]
Great! I bump the version ;)

> And whats the purpose of Polysharp here?

See [github.com/Sergio0694/PolySharp](https://github.com/Sergio0694/PolySharp) -> the lib allows to build your .net 7/C#11 code that has features not supported by .net 6/C#10. Without any code change, your C#11 code builds successfully using the .net 6 SDK. 
The great thing about it is that it doesn't come as another dependency.

**Comment by ChristianSauer** [comment]
Ah ok thanks. Will merge now.

**Pull request merged**
